version: "2"

services:
   web:
      container_name: gunicorn
      restart: always
      image: 'registry.cn-beijing.aliyuncs.com/redaus/xdp'
      ports:
        - 8077:8077
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./vulfocus-api:/usr/src/app
        - /usr/bin/docker:/usr/bin/docker
        - /var/run/docker.sock:/var/run/docker.sock
        - /nfs_data:/nfs_data
      command: /usr/local/bin/gunicorn vulfocus.wsgi:application -w 2 -b :8077
      networks:
          customize_net:
            ipv4_address: 192.168.77.110
   celery:
      container_name: celery
      restart: always
      image: 'registry.cn-beijing.aliyuncs.com/redaus/xdp'
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./vulfocus-api:/usr/src/app
        - /usr/bin/docker:/usr/bin/docker
        - /var/run/docker.sock:/var/run/docker.sock
        - /nfs_data:/nfs_data
      command: /usr/local/bin/celery worker -A vulfocus -l INFO --autoscale 30,5 --logfile ./celery.log
      networks:
          customize_net:
            ipv4_address: 192.168.77.111

   flower:
     container_name: flower
     restart: always
     ports:
       - 5555:5555
     image: 'registry.cn-beijing.aliyuncs.com/redaus/xdp'
     volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./vulfocus-api:/usr/src/app
        - /usr/bin/docker:/usr/bin/docker
        - /var/run/docker.sock:/var/run/docker.sock
        - /nfs_data:/nfs_data
     command: /usr/local/bin/flower --address=0.0.0.0 --port=5555 --broker=redis://:sqsjywl123@192.168.77.79:6379/5
     networks:
       customize_net:
         ipv4_address: 192.168.77.112

   mysql:
      container_name: mysql
      image: 'registry.cn-hangzhou.aliyuncs.com/xxzhang/mysql:5.7'
      volumes:
        - /srv/docker.mysql_data2:/var/lib/mysql
        - ./private/containers/mysql/mysql.conf.d:/etc/mysql/mysql.conf.d
      restart: always
      ports:
        - "3306:3306"
      environment:
       - MYSQL_USER=admin007
       - MYSQL_PASSWORD=myadmin@816
       - MYSQL_DATABASE=qydldb
       - MYSQL_ROOT_PASSWORD=test@1q2w2e4R
      networks:
        customize_net:
          ipv4_address: 192.168.77.101

   redis:
     container_name: redis
     image: 'registry.cn-hangzhou.aliyuncs.com/xxzhang/redis:4.0.9'
     volumes:
       - /srv/docker/redis_data2:/var/lib/redis
       - /etc/localtime:/etc/localtime:ro
     restart: always
     #expose:
     #  - 6379
     ports:
       - 6379:6379
     environment:
       - REDIS_PASSWORD=sqsjywl123
     networks:
       customize_net:
         ipv4_address: 192.168.77.79

   nginx:
     container_name: ngx
     restart: always
     image: "registry.cn-hangzhou.aliyuncs.com/xxzhang/tengine"
     ports:
       - "80:80"
     volumes:
       - /etc/localtime:/etc/localtime:ro
       - ./vulfocus-api/collect_static:/home/collect_static
       - ./dist:/var/www/html
       - ./private/containers/nginx/nginx.conf:/etc/nginx/nginx.conf
       - ./private/containers/nginx/waf-help.conf:/etc/nginx/waf-help.conf
       - ./private/containers/nginx/vhosts:/etc/nginx/vhosts
     networks:
       customize_net:
         ipv4_address: 192.168.77.189

networks:
  customize_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.77.0/24

