"""
Django settings for vulfocus project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import docker
import datetime
import redis
from django.core.management import utils

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# TODO 2021-1-25 load from `config.yaml`
from .conf import config

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.SECRET_KEY


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config.DEBUG

ALLOWED_HOSTS = ["*"]

AUTH_USER_MODEL = "user.UserProfile"

# Application definition
ALLOWED_IMG_SUFFIX = ["jpg", "jpeg", "png"]

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'user',
    # 'corsheaders',
    'dockerapi',
    'network',
    'tasks',
    'layout_image'
]

# redis host
REDIS_HOST = config.REDIS_HOST
# redis port
REDIS_PORT = config.REDIS_PORT
# redis pass
REDIS_PASS = config.REDIS_PASSWORD
if REDIS_PASS:
    CELERY_BROKER_URL = "redis://:%s@%s:%s/0" % (REDIS_PASS, str(REDIS_HOST), str(REDIS_PORT))
    REDIS_POOL = redis.ConnectionPool(host=REDIS_HOST, port=int(REDIS_PORT), password=REDIS_PASS, decode_responses=True, db=1)
else:
    CELERY_BROKER_URL = 'redis://%s:%s/0' % (REDIS_HOST, str(REDIS_PORT))
    REDIS_POOL = redis.ConnectionPool(host=REDIS_HOST, port=int(REDIS_PORT), decode_responses=True,db=1)

#: Only add pickle to this list if your broker is secured
#: from unwanted access (see userguide/security.html)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_TASK_SERIALIZER = 'json'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS_ORIGIN_WHITELIST = [
#     "http://localhost:9527",
# ]
# CORS_ORIGIN_ALLOW_ALL = True

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

JWT_AUTH = {
    # 'JWT_RESPONSE_PAYLOAD_HANDLER':'user.jwt.jwt_response_payload_handler',
    # 指明token的有效期
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=1),
    'JWT_AUTH_HEADER_PREFIX': 'BMH',

}


ROOT_URLCONF = 'vulfocus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vulfocus.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# Session 和y页面的缓存存储, 由于不是ORM，所以很多用户上

SESSION_COOKIE_DOMAIN = config.SESSION_COOKIE_DOMAIN
CSRF_COOKIE_DOMAIN = config.CSRF_COOKIE_DOMAIN
SESSION_COOKIE_AGE = config.SESSION_COOKIE_AGE
SESSION_EXPIRE_AT_BROWSER_CLOSE = config.SESSION_EXPIRE_AT_BROWSER_CLOSE
SESSION_ENGINE = 'redis_sessions.session'
SESSION_REDIS = {
    'host': config.REDIS_HOST,
    'port': config.REDIS_PORT,
    'password': config.REDIS_PASSWORD,
    'db': config.REDIS_DB_SESSION,
    'prefix': 'auth_session',
    'socket_timeout': 1,
    'retry_on_timeout': False
}

MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'
# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DB_OPTIONS = {}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.{}'.format(config.DB_ENGINE.lower()),
        'NAME': config.DB_NAME,
        'HOST': config.DB_HOST,
        'PORT': config.DB_PORT,
        'USER': config.DB_USER,
        'PASSWORD': config.DB_PASSWORD,
        'ATOMIC_REQUESTS': True,
        'OPTIONS': DB_OPTIONS
    },
    # 'mongo': {
    #     'ENGINE': None,
    # }
}

DB_CA_PATH = os.path.join(BASE_DIR, 'data', 'ca.pem')
if config.DB_ENGINE.lower() == 'mysql':
    # DB_OPTIONS['init_command'] = "SET sql_mode='STRICT_TRANS_TABLES'"
    DB_OPTIONS['sql_mode'] = "traditional"
    if os.path.isfile(DB_CA_PATH):
        DB_OPTIONS['ssl'] = {'ca': DB_CA_PATH}
elif config.DB_ENGINE.lower() == 'sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

# bug MySQL does not allow unique CharFields to have a max_length > 255
SILENCED_SYSTEM_CHECKS = ['mysql.E001']

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/
LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

# TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# 默认启动容器最长时间为 60s，可根据实际情况调整
DOCKER_CONTAINER_TIME = 60

DOCKER_HOST = config.DOCKER_HOST
DOCKER_URL = f"tcp://{DOCKER_HOST}:2375"

if DOCKER_URL.startswith("unix:"):
    client = docker.DockerClient(base_url=DOCKER_URL)
    api_docker_client = docker.APIClient(base_url=DOCKER_URL)
else:
    client = docker.DockerClient(DOCKER_URL)
    api_docker_client = docker.APIClient(base_url=DOCKER_URL)

try:
    """
    设置 docker-compose 连接
    """
    os.environ['DOCKER_HOST'] = DOCKER_URL
except Exception as e:
    pass


# 靶场绑定 IP，提供用户访问靶场与 Docker 服务IP保持一致。
try:
    VUL_IP = config.VUL_IP
except:
    VUL_IP = config.DOCKER_HOST

DOCKER_COMPOSE = os.path.join(BASE_DIR, "docker-compose")

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
